name: Build LaTeX document
on:
  push:
    paths:
      - "*.tex"
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Prepare TeX files
        run: |
          python make_tex_files.py
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          extra_system_packages: "py-pygments"
          root_file: |
            "TP_*.tex"
            rappel_complexes.tex
          glob_root_file: true
          continue_on_error: true
      - uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: "*.pdf"
      - name: Zip PDFs
        if: startsWith(github.ref, 'refs/tags/')
        run: zip PDFs.zip -r *.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "PDFs.zip"
