name: Build LaTeX document
on:
  push:
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          extra_system_packages: "py-pygments"
          root_file: |
            seance0.tex
            seance1.tex
            seance2.tex
            seance3.tex
            seance4.tex
